### ISSUE TITLE
Back button?

### ISSUE THREAD

**Issue by ronnietucker** [luksus42/plex-app#7] opened 2018-08-26 19:19 UTC
When watching a movie there's no way to return to the list of movies.

**Comment by luksus42** [comment] 2018-08-27 07:07
Thanks, I will have a look into it.

**Comment by luksus42** [comment] 2018-08-27 19:10
For me it seems to be alright.
Could you please describe the steps you are doing, to reproduce the issue?
What ubports/ubuntu touch version do you use?
Is it possible that just the icon is missing, but the button is there (invisible)?

**Comment by ronnietucker** [comment] 2018-08-27 19:19
I'm using the current ubports 16.04/dev on the BQ M10 tablet.

Screenshots below show my about screen then a movie playing and playing full screen. There's no button to go back to the list of movies.

![screenshot20180827_201618621](https://user-images.githubusercontent.com/10391379/44680621-32151b00-aa36-11e8-8d5f-d691abc596d1.png)
![screenshot20180827_201716618](https://user-images.githubusercontent.com/10391379/44680638-43f6be00-aa36-11e8-84e9-96a5852ea388.png)
![screenshot20180827_201730415](https://user-images.githubusercontent.com/10391379/44680642-4822db80-aa36-11e8-89dd-f26f37e4dc6f.png)

**Comment by luksus42** [comment] 2018-08-27 19:24
ahh I see, you can't leave the fullscreen?
Just do a short tab at the screen and the bottom-bar should appear again.
Then you can leave fullscreen with the button on the right end.

**Comment by ronnietucker** [comment] 2018-08-27 19:25
No no. I can get in/out of full screen no problem. It's just that I can't go from watching a video back to the list of videos to pick something else.

**Comment by luksus42** [comment] 2018-08-27 19:27
Oh ok... can you please try to switch the tablet into portraitmode?

**Comment by ronnietucker** [comment] 2018-08-27 19:29
In portrait mode, I have the video in the bottom half of the screen and the list of movies in the top half.

**Comment by luksus42** [comment] 2018-08-27 19:30
And now you could return to the list?

**Comment by luksus42** [comment] 2018-08-27 19:35
In the bottom, there is the playlist and the player located. If you do not play anything you should be able to open and close it by a short tab on that arrow.
I assume, that the calculation of the playlists size, regarding the screensize, is doing something wrong in landscape mode.

**Comment by ronnietucker** [comment] 2018-08-27 19:40
Yep.

If I play a video in landscape, the only way back is to use portrait mode to get access to the '<' button.

It looks like the brown bar below the playlist bar is sticking out the top of the screen (in landscape).

**Comment by luksus42** [comment] 2018-08-27 19:42
Ok, I will see what I can do, to fix that issue.

**Comment by ronnietucker** [comment] 2018-08-27 19:43
Awesome. Thank you!

**Comment by luksus42** [comment] 2018-09-02 15:24
I just uploaded a new version, where this issue should be fixed. 
Please give it a try and report back here.

**Comment by luksus42** [comment] 2018-09-02 15:30
sorry, needed to "unpublish" the new version, because of some layout bugs... I report back, when its online again.

**Comment by luksus42** [comment] 2018-09-02 19:13
Just published the fixed version.

**Closed as completed by luksus42** 2018-09-02 19:13 UTC
Labels: bug

**Comment by ronnietucker** [comment] 2018-09-02 19:43
Beautiful. Works a treat.

Not sure if they were there before, but I didn't see AUDIO or SUBS buttons in the previous version.

**Many thanks!**

**Comment by luksus42** [comment] 2018-09-02 19:48
This is a new feature, I was working on:
https://github.com/luksus42/plex-app/issues/6
